// Verified direct-image URLs for the "direct-image sources only" snapshot tier.
// Keyed as "<resort-slug>-<tier>" to match the KV keys the Worker reads/writes.
// Only entries confirmed by fetching the URL and checking Content-Type: image/*
// belong here -- see the webcam links in src/data/resorts.ts for the full,
// larger set of click-through webcam pages (most of which are JS viewers with
// no direct image URL, and are intentionally not captured).
export const WEBCAM_SOURCES = {
  "st-anton-base": "https://images.bergfex.at/webcams/?id=362&2",
  "st-anton-mid": "https://images.bergfex.at/webcams/?id=799&2",
  "st-anton-summit": "https://images.bergfex.at/webcams/?id=275&2",
  "lech-base": "https://images.bergfex.at/webcams/?id=10331&2",
  "lech-mid": "https://images.bergfex.at/webcams/?id=3482&2",
  "lech-summit": "https://images.bergfex.at/webcams/?id=3483&2",
  "kitzbuhel-base": "https://www.foto-webcam.eu/webcam/zielhaus-hahnenkamm/current/1200.jpg",
  "kitzbuhel-mid": "https://www.foto-webcam.eu/webcam/starthaus-hahnenkamm/current/1200.jpg",
  "kitzbuhel-summit": "https://images.bergfex.at/webcams/?id=24977&2",
  "solden-base": "https://images.bergfex.at/webcams/?id=22557&2",
  "solden-mid": "https://images.bergfex.at/webcams/?id=21829&2",
  "solden-summit": "https://images.bergfex.at/webcams/?id=3014&2",
  "ischgl-mid": "https://images.bergfex.at/webcams/?id=62&2",
  "ischgl-summit": "https://images.bergfex.at/webcams/?id=2516&2",
  "mayrhofen-base": "https://images.bergfex.at/webcams/?id=19341&2",
  "mayrhofen-mid": "https://images.bergfex.at/webcams/?id=886&2",
  "mayrhofen-summit": "https://images.bergfex.at/webcams/?id=13148&2",
  "obergurgl-base": "https://images.bergfex.at/webcams/?id=1306",
  "obergurgl-mid": "https://images.bergfex.at/webcams/?id=809",
  "obergurgl-summit": "https://images.bergfex.at/webcams/?id=412",
  "saalbach-base": "https://images.bergfex.at/webcams/?id=24789",
  "saalbach-mid": "https://images.bergfex.at/webcams/?id=11396",
  "saalbach-summit": "https://images.bergfex.at/webcams/?id=731",
  "kaprun-base": "https://www.foto-webcam.eu/webcam/zellamsee/current/1200.jpg",
  "kaprun-mid": "https://images.bergfex.at/webcams/?id=521",
  "kaprun-summit": "https://images.bergfex.at/webcams/?id=520",
  "schladming-base": "https://images.bergfex.at/webcams/?id=11002",
  "schladming-mid": "https://images.bergfex.at/webcams/?id=977",
  "schladming-summit": "https://images.bergfex.at/webcams/?id=378",
  "bad-gastein-base": "https://images.bergfex.at/webcams/?id=5516",
  "bad-gastein-mid": "https://images.bergfex.at/webcams/?id=7353",
  "bad-gastein-summit": "https://images.bergfex.at/webcams/?id=13961",
  "sestriere-base": "https://images.bergfex.at/webcams/?id=22828",
  "sestriere-mid": "https://images.bergfex.at/webcams/?id=22830",
  "sestriere-summit": "https://images.bergfex.at/webcams/?id=22829",
  "cervinia-mid": "https://images.bergfex.at/webcams/?id=4746",
  "cervinia-summit": "https://images.bergfex.at/webcams/?id=11812",
};
